# Generated by Django 5.1.4 on 2026-04-20 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('protocol', models.CharField(choices=[('REST', 'REST'), ('SOAP', 'SOAP'), ('MQ', 'MQ'), ('SFTP', 'SFTP'), ('BATCH', 'Batch')], max_length=8)),
                ('target_system', models.CharField(blank=True, max_length=64)),
                ('endpoint', models.CharField(blank=True, max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterfaceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUCCESS', '성공'), ('FAIL', '실패')], max_length=8)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('request_summary', models.TextField(blank=True)),
                ('response_summary', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='interfaces.interface')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
    ]
