# Generated by Django 5.1.4 on 2026-04-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='config_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
