# Generated by Django 5.1.4 on 2026-04-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0002_interface_config_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='operation_type',
            field=models.CharField(blank=True, choices=[('REST_GET_QUERY', 'REST 조회 (GET)'), ('SOAP_QUERY', 'SOAP 조회'), ('MQ_PUBLISH', 'MQ 발행'), ('MQ_CONSUME', 'MQ 수신'), ('MQ_CONSUME_PROCESS', 'MQ 수신 → 가공 → 저장'), ('SFTP_DOWNLOAD', 'SFTP 다운로드'), ('SFTP_UPLOAD', 'SFTP 업로드'), ('BATCH_SCHEDULED', 'Batch 스케줄 실행')], help_text='프로토콜별 세부 동작', max_length=24),
        ),
        migrations.AddField(
            model_name='interface',
            name='schedule_cron',
            field=models.CharField(blank=True, help_text='cron 표기 (예: "0 2 * * *" = 매일 새벽 2시). BATCH/SFTP 일 때만 사용', max_length=64),
        ),
    ]
