"""
Django settings for portal project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p%z&a+$u!3$7t4v$x023%=^+_1nfg*nq8b@o-q*ysoaxgi4k4p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    'rest_framework',
    'drf_spectacular',
    'django_htmx',

    'apps.core',
    'apps.accounts',
    'apps.monitoring',
    'apps.interfaces',
    'apps.evaluation',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

ROOT_URLCONF = 'portal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.core.context_processors.nav',
            ],
        },
    },
]

WSGI_APPLICATION = 'portal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ── 인터페이스 실행 모드 ─────────────────────────────────────
# True  : 실제 어댑터 (requests / zeep / paramiko / subprocess / pika) 호출
# False : Mock 응답 (개발·데모·테스트 기본)
# 인터페이스별 override: config_json 에 "live": true/false 키로 개별 지정 가능
INTERFACE_LIVE_MODE = False

# 실제 호출 시 공통 제한
INTERFACE_HTTP_TIMEOUT = 30           # REST/SOAP 타임아웃 (초)
INTERFACE_SFTP_TIMEOUT = 30           # SFTP 연결 타임아웃 (초)
INTERFACE_BATCH_TIMEOUT = 3600        # BATCH 최대 실행 시간 (초)
INTERFACE_RESPONSE_MAX_CHARS = 4000   # response/request summary 저장 길이 제한
INTERFACE_RETRY_MAX = 1               # 실패 시 재시도 횟수 (0=재시도 없음)
INTERFACE_RETRY_BACKOFF = 0.5         # 재시도 대기 (초, 지수 증가)


# ── Celery / Beat ─────────────────────────────────────────
# broker/backend 는 환경변수로 덮어쓸 수 있음 (docker-compose 에서 redis://redis:6379 로 연결)
import os as _os
from celery.schedules import crontab as _crontab

CELERY_BROKER_URL = _os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = _os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/1')
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = False
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SOFT_TIME_LIMIT = 600
CELERY_TASK_TIME_LIMIT = 900
# 테스트/개발 환경에서 broker 없이도 작업이 인라인 실행되도록
CELERY_TASK_ALWAYS_EAGER = _os.environ.get('CELERY_TASK_ALWAYS_EAGER', 'True').lower() == 'true'
CELERY_TASK_EAGER_PROPAGATES = True

CELERY_BEAT_SCHEDULE = {
    # 매분: 활성 인터페이스 중 cron 이 현재 분에 걸리는 것을 trigger
    'dispatch-scheduled-interfaces': {
        'task': 'apps.interfaces.tasks.dispatch_interfaces',
        'schedule': _crontab(minute='*'),
    },
    # 매일 18:00 KST: 시세 스냅샷 전진
    'refresh-market-data-daily': {
        'task': 'apps.evaluation.tasks.refresh_market_data',
        'schedule': _crontab(minute=0, hour=18),
    },
    # 매월 1일 02:00: 전월 인건비 안분
    'allocate-salary-monthly': {
        'task': 'apps.evaluation.tasks.allocate_salary_previous_month',
        'schedule': _crontab(minute=0, hour=2, day_of_month=1),
    },
}
